version: 3
endpoint: http://hasura:8080
admin_secret: myhasurasecret
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000 