# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install poetry
        run: |
          python -m pip install poetry
          poetry config virtualenvs.create false

      - name: Build release distributions
        run: |
          poetry build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # NOTE: Before this will work, you need to configure PyPI trusted publishing:
    # 1. Go to https://pypi.org/manage/account/publishing/
    # 2. Add a new pending publisher with:
    #    - Owner: Props-Labs
    #    - Repository: mesh-os
    #    - Workflow name: Upload Python Package
    #    - Environment: pypi
    environment:
      name: pypi
      url: https://pypi.org/p/mesh-os

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
